package indg.com.cover2protect.model.nutrition

import java.io.Serializable

class Fields : Serializable{
     var allergen_contains_eggs: String=""
     var allergen_contains_fish: String=""
     var allergen_contains_gluten: String=""
     var allergen_contains_milk: String=""
     var allergen_contains_peanuts: String=""
     var allergen_contains_shellfish: String=""
     var allergen_contains_soybeans: String=""
     var allergen_contains_tree_nuts: String=""
     var allergen_contains_wheat: String=""
     var brand_id: String=""
     var brand_name: String=""
     var item_description: String=""
     var item_id: String=""
     var item_name: String=""
     var nf_calcium_dv: String=""
     var nf_calories: String=""
     var nf_calories_from_fat: String=""
     var nf_cholesterol: String=""
     var nf_dietary_fiber: String=""
     var nf_ingredient_statement: String=""
     var nf_iron_dv: String=""
     var nf_monounsaturated_fat: String=""
     var nf_polyunsaturated_fat: String=""
     var nf_protein: String=""
     var nf_refuse_pct: String=""
     var nf_saturated_fat: String=""
     var nf_serving_size_qty: String=""
     var nf_serving_size_unit: String=""
     var nf_serving_weight_grams: String=""
     var nf_servings_per_container: String=""
     var nf_sodium: String=""
     var nf_sugars: String=""
     var nf_total_carbohydrate: String=""
     var nf_total_fat: String=""
     var nf_trans_fatty_acid: String=""
     var nf_vitamin_a_dv: String=""
     var nf_vitamin_c_dv: String=""
     var nf_water_grams: String=""
     var old_api_id: String=""
     var updated_at: String=""
 }